default:
  hooks:
    pre_get_sources_script:
      - git config --global protocol.file.allow always

stages:
  - test
  - build-hw
  - release

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

.docker-image-hw:
  tags:
    - enzian-docker
    - vivado
  image: "registry.ethz.ch/project-openenzian/ci-images/spinal-verilator:ubuntu-22.04"

fast-tests-eci:
  extends: .docker-image-hw
  stage: test
  script:
    - mill gen.test.testOnly lauberhorn.host.eci.NicSim -- -l org.scalatest.tags.Slow -l lauberhorn.sim.tags.Tx
  artifacts:
    when: on_failure
    paths:
      - simWorkspace/**/sim_transcript.log.gz
      - simWorkspace/**/wave.fst

.build-hw:
  extends: .docker-image-hw
  stage: build-hw
  needs:
    - fast-tests-eci
  before_script:
    - source /opt/Xilinx/Vivado/2023.2/settings64.sh
  script:
    - mill --no-server $PIONIC_DESIGN.generateBitstream

# build-hw-pcie:
#   extends: .build-hw
#   variables:
#     PIONIC_DESIGN: pcie
#   artifacts:
#     paths:
#       - out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/pio-nic-pcie.bit
#       - out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/pio-nic-pcie.ltx
#       - out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/design_1_wrapper_postroute_physopt.dcp
#       - hw/gen/*/*.h
#       - sw/devices/pionic_*.dev

build-hw-eci:
  extends: .build-hw
  variables:
    PIONIC_DESIGN: eci
  artifacts:
    paths:
      - out/eci/vivadoProject.dest/shell_lauberhorn-eci_routed.dcp
      - out/eci/vivadoProject.dest/shell_lauberhorn-eci.bit
      - out/eci/vivadoProject.dest/shell_lauberhorn-eci.ltx
      - hw/gen/*/*.h
      - sw/devices/pionic_*.dev

publish:
  stage: release
  image: registry.ethz.ch/project-openenzian/ci-images/publish:ubuntu-22.04
  script: /publish_artifacts
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    # - job: build-hw-pcie
    #   artifacts: true
    - job: build-hw-eci
      artifacts: true
  variables:
    PROJECT_ID: 47960
    PACKAGE_NAME: release
    RELEASE_NAME: 'Release $CI_COMMIT_TAG'
    RELEASE_TAG: '$CI_COMMIT_TAG'
    ARTIFACT_PATHS: |
      sw/pcie/pionic-test
      sw/eci/pionic-test
      out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/pio-nic-pcie.bit
      out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/pio-nic-pcie.ltx
      out/pcie/vivadoProject.dest/pio-nic-pcie/pio-nic-pcie.runs/impl_1/design_1_wrapper_postroute_physopt.dcp
      out/eci/vivadoProject.dest/shell_lauberhorn-eci_routed.dcp
      out/eci/vivadoProject.dest/shell_lauberhorn-eci.bit
      out/eci/vivadoProject.dest/shell_lauberhorn-eci.ltx
