stages:
  - tests
  - build_bitstream
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

tests:
  tags:
    - enzian-docker
  image: "registry.ethz.ch/project-openenzian/ci-images/pionic-tools:latest"
  stage: tests
  script:
    - mill gen.test -l org.scalatest.tags.Slow -l pionic.tags.Formal

# WIP: pull static shell release
# build_bitstream:
#   tags:
#     - enzian-shell
#     - vivado
#   stage: build_bitstream
#   script:
#     - curl -
#     - mill eci.generateVerilog
#   artifacts:
#     - out/eci/vivadoProject.dest/shell_pio-nic-eci_routed.dcp
#     - out/eci/vivadoProject.dest/shell_pio-nic-eci.bit
#     - out/eci/vivadoProject.dest/shell_pio-nic-eci.ltx

# release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   rules:
#     - if: '$CI_COMMIT_TAG'
#   needs:
#     - job: build_bitstream
#       artifacts: true
#   release:
#     tag_name: '$CI_COMMIT_TAG'
#     description: 'Release for version $CI_COMMIT_TAG'
