version = "3.7.15"
runner.dialect = scala213
fileOverride {
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/spinalhdl/project/package.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/spinalhdl/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/module.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/deps/spinalhdl/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/spinalhdl/project/Version.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/.bsp/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/deps/spinalhdl/project/Version.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/spinalhdl/project/Version.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/deps/package.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/blocks/deps/spinalhdl/project/package.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/deps/package.mill/**" {
     runner.dialect = scala3
  }
}
