#ifndef LAUBERHORN_INTTYPES_H
#define LAUBERHORN_INTTYPES_H

// Define the PRIx64 macro used by the display functions generated by Mackerel.
// The actual snprintf definition is found in mackerel_support/mackerel.h

#define PRIx64 "llx"

#endif // LAUBERHORN_INTTYPES_H