// SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0-only
// Copyright (c) 2025 Pengcheng Xu

#ifndef LAUBERHORN_INTTYPES_H
#define LAUBERHORN_INTTYPES_H

// Define the PRIx64 macro used by the display functions generated by Mackerel.
// The actual snprintf definition is found in mackerel_support/mackerel.h

#define PRIx8 "x"
#define PRIx16 "x"
#define PRIx32 "x"
#define PRIx64 "llx"

#endif // LAUBERHORN_INTTYPES_H