/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <stdio.h>

int add(CLIENT *clnt, int a, int b) {
  add_call arg = {.a = a, .b = b};
  add_resp *result = add_1(&arg, clnt);
  if (!result) {
    clnt_perror(clnt, "call failed");
    return -1;
  } else
    return result->sum;
}

void add_prog_1(char *host) {
  CLIENT *clnt;
  add_call add_1_arg;

#ifndef DEBUG
  clnt = clnt_create(host, ADD_PROG, ADD_VERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  for (int i = 0; i < 100; ++i) {
    for (int j = 0; j < 100; ++j) {
      printf("%d + %d = %d\n", i, j, add(clnt, i, j));
    }
  }

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  add_prog_1(host);
  exit(0);
}
